# Generated by Django 6.0 on 2025-12-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='authentic',
            field=models.BooleanField(default=True, help_text='Set to True for authentic products, False for replica products', verbose_name='Authentic Product Banner'),
        ),
    ]
