# Generated by Django 6.0 on 2026-01-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_authentic'),
        ('core', '0002_banner_authentic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredsection',
            name='category',
        ),
        migrations.RemoveField(
            model_name='featuredsection',
            name='section_type',
        ),
        migrations.AlterField(
            model_name='featuredsection',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Select products to display in this section', related_name='featured_in_sections', to='catalog.product', verbose_name='Products'),
        ),
    ]
