# Generated by Django 6.0 on 2026-01-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_section_type_and_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredsection',
            name='section_type',
            field=models.CharField(choices=[('new', 'New Arrivals'), ('featured', 'Featured Products'), ('sale', 'On Sale'), ('popular', 'Popular Products'), ('custom', 'Custom Section')], default='custom', help_text='Label/category for this section', max_length=20, verbose_name='Section Type'),
        ),
    ]
