# Generated by Django 5.2.8 on 2026-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_section_type_back'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_tracking_code', models.TextField(blank=True, default='', help_text='Paste your tracking pixel script here (e.g., Meta Pixel base code)', verbose_name='Site Tracking Code')),
                ('meta_pixel_id', models.CharField(blank=True, default='', help_text='Used by backend to send Conversion API events', max_length=50, verbose_name='Meta Pixel ID')),
                ('meta_access_token', models.TextField(blank=True, default='', help_text='Required for Conversion API authentication. Never exposed to frontend.', verbose_name='Meta Conversion API Access Token')),
                ('enable_conversion_api', models.BooleanField(default=False, help_text='Allows turning server-side tracking on/off', verbose_name='Enable Conversion API')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
    ]
