# Generated by Django 5.2.8 on 2026-04-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file for the banner', null=True, upload_to='banners/videos/%Y/%m/', verbose_name='Banner Video'),
        ),
        migrations.AddField(
            model_name='banner',
            name='video_url',
            field=models.URLField(blank=True, help_text='Or provide a video URL (e.g. YouTube, Vimeo, or direct link)', max_length=500, null=True, verbose_name='Banner Video URL'),
        ),
    ]
