# Generated by Django 5.2.8 on 2026-04-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_banner_video_banner_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Page Title')),
                ('slug', models.SlugField(help_text='URL-friendly name (e.g. about-us)', max_length=200, unique=True, verbose_name='Slug')),
                ('content', models.TextField(help_text='HTML content for the page', verbose_name='Content')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'pages',
                'ordering': ['title'],
            },
        ),
    ]
