# Generated by Django 6.0 on 2025-12-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authentic',
            field=models.BooleanField(default=True, help_text='Indicates if the product is authentic'),
        ),
    ]
